# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ObjGen.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cObjGen.proto\"M\n\rSatelliteAddr\x12\r\n\x05SatID\x18\x01 \x01(\x05\x12\x11\n\tsate_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"1\n\x0cLoadResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x12\r\n\x05ObjID\x18\x02 \x01(\x05\"]\n\x0cPositionInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0b\n\x03\x61lt\x18\x02 \x01(\x02\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0b\n\x03lng\x18\x04 \x01(\x02\x12\x13\n\x0btarget_name\x18\x05 \x01(\t\"\x8a\x01\n\x0bObjPosition\x12\r\n\x05ObjID\x18\x01 \x01(\x05\x12\x12\n\ndelta_time\x18\x02 \x01(\x02\x12\x11\n\tdelta_lng\x18\x03 \x01(\x02\x12\x11\n\tdelta_lat\x18\x04 \x01(\x02\x12\x0b\n\x03sog\x18\x05 \x01(\x02\x12\x0b\n\x03\x63og\x18\x06 \x01(\x02\x12\x0b\n\x03lng\x18\x07 \x01(\x02\x12\x0b\n\x03lat\x18\x08 \x01(\x02\"&\n\nTrackPoint\x12\x0b\n\x03lng\x18\x01 \x01(\x02\x12\x0b\n\x03lat\x18\x02 \x01(\x02\"/\n\x0cPredictTrack\x12\x1f\n\npred_point\x18\x01 \x03(\x0b\x32\x0b.TrackPoint\"!\n\x0eObjPosResponse\x12\x0f\n\x07seq_len\x18\x01 \x01(\x05\"\x18\n\x07ObjInfo\x12\r\n\x05ObjID\x18\x01 \x01(\x05\x32\x37\n\x06ObjGen\x12-\n\x0cStartLoadObj\x12\x0e.SatelliteAddr\x1a\r.LoadResponse2h\n\tSatServer\x12/\n\x0eGetObjPosition\x12\x0c.ObjPosition\x1a\x0f.ObjPosResponse\x12*\n\x0fPredictObjTrack\x12\x08.ObjInfo\x1a\r.PredictTrackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ObjGen_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SATELLITEADDR']._serialized_start=16
  _globals['_SATELLITEADDR']._serialized_end=93
  _globals['_LOADRESPONSE']._serialized_start=95
  _globals['_LOADRESPONSE']._serialized_end=144
  _globals['_POSITIONINFO']._serialized_start=146
  _globals['_POSITIONINFO']._serialized_end=239
  _globals['_OBJPOSITION']._serialized_start=242
  _globals['_OBJPOSITION']._serialized_end=380
  _globals['_TRACKPOINT']._serialized_start=382
  _globals['_TRACKPOINT']._serialized_end=420
  _globals['_PREDICTTRACK']._serialized_start=422
  _globals['_PREDICTTRACK']._serialized_end=469
  _globals['_OBJPOSRESPONSE']._serialized_start=471
  _globals['_OBJPOSRESPONSE']._serialized_end=504
  _globals['_OBJINFO']._serialized_start=506
  _globals['_OBJINFO']._serialized_end=530
  _globals['_OBJGEN']._serialized_start=532
  _globals['_OBJGEN']._serialized_end=587
  _globals['_SATSERVER']._serialized_start=589
  _globals['_SATSERVER']._serialized_end=693
# @@protoc_insertion_point(module_scope)
