# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ObjGen_pb2 as ObjGen__pb2


class ObjGenStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLoadObj = channel.unary_unary(
                '/ObjGen/StartLoadObj',
                request_serializer=ObjGen__pb2.SatelliteAddr.SerializeToString,
                response_deserializer=ObjGen__pb2.LoadResponse.FromString,
                )


class ObjGenServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLoadObj(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjGenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLoadObj': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLoadObj,
                    request_deserializer=ObjGen__pb2.SatelliteAddr.FromString,
                    response_serializer=ObjGen__pb2.LoadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ObjGen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjGen(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLoadObj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ObjGen/StartLoadObj',
            ObjGen__pb2.SatelliteAddr.SerializeToString,
            ObjGen__pb2.LoadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SatServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjPosition = channel.unary_unary(
                '/SatServer/GetObjPosition',
                request_serializer=ObjGen__pb2.ObjPosition.SerializeToString,
                response_deserializer=ObjGen__pb2.ObjPosResponse.FromString,
                )
        self.PredictObjTrack = channel.unary_unary(
                '/SatServer/PredictObjTrack',
                request_serializer=ObjGen__pb2.ObjInfo.SerializeToString,
                response_deserializer=ObjGen__pb2.PredictTrack.FromString,
                )


class SatServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictObjTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SatServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjPosition,
                    request_deserializer=ObjGen__pb2.ObjPosition.FromString,
                    response_serializer=ObjGen__pb2.ObjPosResponse.SerializeToString,
            ),
            'PredictObjTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictObjTrack,
                    request_deserializer=ObjGen__pb2.ObjInfo.FromString,
                    response_serializer=ObjGen__pb2.PredictTrack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SatServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SatServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SatServer/GetObjPosition',
            ObjGen__pb2.ObjPosition.SerializeToString,
            ObjGen__pb2.ObjPosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictObjTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SatServer/PredictObjTrack',
            ObjGen__pb2.ObjInfo.SerializeToString,
            ObjGen__pb2.PredictTrack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
