# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ObjGen_pb2 as ObjGen__pb2


class ObjGenStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLoadObj = channel.unary_unary(
                '/ObjGen/StartLoadObj',
                request_serializer=ObjGen__pb2.SatelliteAddr.SerializeToString,
                response_deserializer=ObjGen__pb2.LoadResponse.FromString,
                )
        self.GetObjPos = channel.unary_unary(
                '/ObjGen/GetObjPos',
                request_serializer=ObjGen__pb2.Obj.SerializeToString,
                response_deserializer=ObjGen__pb2.ObjPos.FromString,
                )


class ObjGenServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartLoadObj(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjGenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartLoadObj': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLoadObj,
                    request_deserializer=ObjGen__pb2.SatelliteAddr.FromString,
                    response_serializer=ObjGen__pb2.LoadResponse.SerializeToString,
            ),
            'GetObjPos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjPos,
                    request_deserializer=ObjGen__pb2.Obj.FromString,
                    response_serializer=ObjGen__pb2.ObjPos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ObjGen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjGen(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartLoadObj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ObjGen/StartLoadObj',
            ObjGen__pb2.SatelliteAddr.SerializeToString,
            ObjGen__pb2.LoadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ObjGen/GetObjPos',
            ObjGen__pb2.Obj.SerializeToString,
            ObjGen__pb2.ObjPos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
