# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SatCom_pb2 as SatCom__pb2


class SatComStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommuWizSat = channel.stream_stream(
                '/SatCom/CommuWizSat',
                request_serializer=SatCom__pb2.Sat2BaseInfo.SerializeToString,
                response_deserializer=SatCom__pb2.Base2SatInfo.FromString,
                )
        self.ReceiveFromUnity_template = channel.stream_stream(
                '/SatCom/ReceiveFromUnity_template',
                request_serializer=SatCom__pb2.Unity2BaseInfo_template.SerializeToString,
                response_deserializer=SatCom__pb2.Base2UnityInfo.FromString,
                )
        self.SendToUnity = channel.stream_unary(
                '/SatCom/SendToUnity',
                request_serializer=SatCom__pb2.Base2UnityInfo.SerializeToString,
                response_deserializer=SatCom__pb2.Unity2BaseInfo.FromString,
                )


class SatComServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommuWizSat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveFromUnity_template(self, request_iterator, context):
        """卫星作为client，向基站发信，两端都是流的方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendToUnity(self, request_iterator, context):
        """可以用的方法，unity端持续发目标的坐标信息，基站持续接收并返回那些哪些卫星正在跟踪以及目标坐标信息
        最后需要实现的方法，基站作为client，持续发送卫星跟踪信息给unity端，unity最后返回一个message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SatComServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommuWizSat': grpc.stream_stream_rpc_method_handler(
                    servicer.CommuWizSat,
                    request_deserializer=SatCom__pb2.Sat2BaseInfo.FromString,
                    response_serializer=SatCom__pb2.Base2SatInfo.SerializeToString,
            ),
            'ReceiveFromUnity_template': grpc.stream_stream_rpc_method_handler(
                    servicer.ReceiveFromUnity_template,
                    request_deserializer=SatCom__pb2.Unity2BaseInfo_template.FromString,
                    response_serializer=SatCom__pb2.Base2UnityInfo.SerializeToString,
            ),
            'SendToUnity': grpc.stream_unary_rpc_method_handler(
                    servicer.SendToUnity,
                    request_deserializer=SatCom__pb2.Base2UnityInfo.FromString,
                    response_serializer=SatCom__pb2.Unity2BaseInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SatCom', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SatCom(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommuWizSat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SatCom/CommuWizSat',
            SatCom__pb2.Sat2BaseInfo.SerializeToString,
            SatCom__pb2.Base2SatInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveFromUnity_template(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SatCom/ReceiveFromUnity_template',
            SatCom__pb2.Unity2BaseInfo_template.SerializeToString,
            SatCom__pb2.Base2UnityInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendToUnity(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SatCom/SendToUnity',
            SatCom__pb2.Base2UnityInfo.SerializeToString,
            SatCom__pb2.Unity2BaseInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SatServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjPosition = channel.unary_unary(
                '/SatServer/GetObjPosition',
                request_serializer=SatCom__pb2.ObjPosition.SerializeToString,
                response_deserializer=SatCom__pb2.ObjPosResponse.FromString,
                )
        self.PredictObjTrack = channel.unary_unary(
                '/SatServer/PredictObjTrack',
                request_serializer=SatCom__pb2.ObjInfo.SerializeToString,
                response_deserializer=SatCom__pb2.PredictTrack.FromString,
                )


class SatServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictObjTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SatServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjPosition,
                    request_deserializer=SatCom__pb2.ObjPosition.FromString,
                    response_serializer=SatCom__pb2.ObjPosResponse.SerializeToString,
            ),
            'PredictObjTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictObjTrack,
                    request_deserializer=SatCom__pb2.ObjInfo.FromString,
                    response_serializer=SatCom__pb2.PredictTrack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SatServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SatServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SatServer/GetObjPosition',
            SatCom__pb2.ObjPosition.SerializeToString,
            SatCom__pb2.ObjPosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictObjTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SatServer/PredictObjTrack',
            SatCom__pb2.ObjInfo.SerializeToString,
            SatCom__pb2.PredictTrack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
